name: w2s
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  animated_splash_screen: 1.1.0
  cupertino_icons: ^1.0.2
  expansion_tile_card: 2.0.0
  flutter:
    sdk: flutter
  flutter_native_splash: 1.3.3
  font_awesome_flutter: 9.2.0
  get: 4.6.1
  get_storage: 2.0.3
  http: 0.13.4
  image_picker: 0.8.4+4
  lottie: 1.2.1
  page_transition: 2.0.1-nullsafety.0
  shimmer_animation: ^2.1.0+1

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/brand/logo.png"
  adaptive_icon_background: #ffffff
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/brand/logo.png
  android_gravity: center

flutter:
  assets:
    - assets/
    - assets/brand/
    - assets/lottie/
  uses-material-design: true
