name: w2s
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  http: 0.13.4
  font_awesome_flutter: 9.2.0
  get_storage: 2.0.3
  image_picker: 0.8.4+4
  flutter_native_splash: 1.3.3
  animated_splash_screen: 1.1.0
  page_transition: 2.0.1-nullsafety.0
  lottie: 1.2.1
  expansion_tile_card: 2.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter_native_splash: 
  color: '#ffffff'
  image: assets/brand/logo.png
  android_gravity: center

flutter: 
  assets: 
    - assets/
    - assets/brand/
    - assets/lottie/
  uses-material-design: true

